### ISSUE TITLE
font blurry in 5.4.1 version

### ISSUE THREAD

**Issue by wikithink** [A-Herzog/Warteschlangensimulator#10]
Dear author of the Queue Simulator,

Thank you very much for your hard work and selfless contribution. I have been able to use this software for queue simulation, which has greatly helped me in my work. I used version 5.1.0 in the past, but today I updated to the latest version (5.4.1) and noticed that the font appears too blurry compared to before on my Windows 10 computer. I am not sure what the reason could be. I downloaded the software in zip format, and my JDK version is 1.8.0. I am reaching out to you for assistance and hope to receive your help.

Thank you very much.

**Comment by A-Herzog** [comment]
The fonts are rendered by the JDK. Java before version 9 was not able to handle Windows display scaling (which applies to nearly all notebook displays and all desktop displays with more than FullHD). This results in either tiny Java application windows or in a burry look (due to Windows image based scaling). If you upgrade to Java version 9 or higher, this problem will be gone. (See also [JEP263]( https://openjdk.org/jeps/263).) That's what I mean by writing "when using a high DPI display, Java 11 or higher is recommended" in the system requirements on the [homepage]( https://a-herzog.github.io/Warteschlangensimulator/). The "System requirements: Java 8 or higher (when using a ..." does not mean that Java 8 is recommended. It only means that Java 8 is required as the absolute minimum. Warteschlangensimulator runs very well on all newer Java version. Java 8 was released in 2014 one year before Windows 10 arrived. It does not know about the progress made on hardware since then.

There is nothing I can do about this from the side of my Java code.
If you are using a system with desktop scaling, please update to a Java version which supports this.
